---
- name: 
  hosts: all
  become: true
  vars:
    git_repository: "https://github.com/Olmy2016/AnsibleRoles.git"
    git_branch: "main"
  tasks:
    - name: Create
      file:
        path: /etc/ansible/roles
        state: directory
        mode: '0755'
    - name:
      git:
        repo: "{{ git_repository }}"
        dest: "/etc/ansible/roles"
        version: "{{ git_branch }}"